### ISSUE TITLE
Some genes are missing in the output 

### ISSUE THREAD

**Issue by hailiangmei** [biopet/refflatsstats#9]
Here is how to reproduce this error on SHARK.

``
module load biopet/dev

biopet tool RefflatStats -a /exports/genomes/species/M.musculus/GRCm38_
no_alt/annotation/features/ensembl_88/Mus_musculus.GRCm38.88.refflat -R /exports/genomes/species/M.musculus/GRCm38_no_alt/reference.fa -g gene.
tsv -t transcript.tsv -e exon.tsv -i intron.tsv

``

Then in gene.tsv, we missed 4 genes: ENSMUSG00000074985, ENSMUSG00000102367, ENSMUSG00000109806, ENSMUSG00000110991

**Comment by DavyCats** [comment]
Solved by #10
